apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-execution
  labels:
    app: codex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codex
  template:
    metadata:
      labels:
        app: codex
    spec:
      containers:
      # - name: server
      #   image: maheshaila01/codex:server
      #   ports:
      #   - containerPort: 8080
      #   - containerPort: 9090
      - name: worker
        image: maheshaila01/codex:worker
      - name: rabbitmq
        image: maheshaila01/codex:rabbitmq
        ports:
        - containerPort: 5672
      - name: redis
        image: maheshaila01/codex:redis
        ports:
        - containerPort: 6379
      
