on:
  workflow_dispatch:
    inputs:
      use-windows:
        type: boolean
        description: "Docker windows OS"
        default: true
        required: false

jobs:
  dynamic-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Set OS variable
        id: set-os
        run: |
          if [ "${{ inputs.use-windows }}" == "true" ]; then
            echo "os=windows-latest" >> $GITHUB_ENV
          else
            echo "os=ubuntu-latest" >> $GITHUB_ENV
          fi

  run-job:
    needs: dynamic-runner
    runs-on: ${{ env.os }}
    steps:
      - name: Run only on Ubuntu
        if: ${{ env.os == 'ubuntu-latest' }}
        run: echo "Running on Ubuntu"

      - name: Run only on Windows
        if: ${{ env.os == 'windows-latest' }}
        run: echo "Running on Windows"
