on:
  workflow_dispatch:
    inputs:
      use-windows:
        type: boolean
        description: "Docker windows OS"
        default: true
        required: false

jobs:
  dynamic-runner:
    runs-on: ubuntu-latest
    outputs:
      os: ${{ steps.set-os.outputs.os }}
    steps:
      - name: Set OS variable
        id: set-os
        run: |
          if [ '${{ inputs.use-windows }}' == 'true' ]; then
            echo "os=windows-latest" >> $GITHUB_ENV
            echo "para=docker" >> $GITHUB_ENV
            echo "::set-output name=os::windows-latest"
          else
            echo "os=ubuntu-latest" >> $GITHUB_ENV
            echo "::set-output name=os::ubuntu-latest"
          fi
          
  run-job:
    needs: dynamic-runner
    runs-on: ${{ needs.dynamic-runner.outputs.os }}
    steps:
      - name: Run only on Ubuntu
        if: ${{ needs.dynamic-runner.outputs.os == 'ubuntu-latest' }}
        run: echo "Running on Ubuntu"
      - name: Run only on Windows
        if: ${{ needs.dynamic-runner.outputs.os == 'windows-latest' }}
        run: echo needs.dynamic-runner.outputs.para
