on:
  workflow_dispatch:
    inputs:
      use-windows:
        type: boolean
        description: "Docker windows OS"
        default: true
        required: false

jobs:
  dynamic-runner:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            condition: ${{ inputs.use-windows == 'false' }}
          - os: windows-latest
            condition: ${{ inputs.use-windows == 'true' }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Run only on Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' && inputs.use-windows == 'false' }}
        run: echo "Running on Ubuntu"

      - name: Run only on Windows
        if: ${{ matrix.os == 'windows-latest' && inputs.use-windows == 'true' }}
        run: echo "Running on Windows"
