name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and Push Docker Image - Server
        uses: docker/build-push-action@v5
        with:
          context: ./server/
          push: true
          tags: maheshaila01/codex:server
      -
        name: Build and Push Docker Image - Worker
        uses: docker/build-push-action@v5
        with:
          context: ./worker/
          push: true
          tags: maheshaila01/codex:worker

# jobs:
#   build-docker:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2

#     - name: Build and Push Docker Image - Server
#       uses: mr-smithers-excellent/docker-build-push@v4
#       with:
#         image: maheshaila01/codex
#         tags: server,latest
#         directory: ./server
#         dockerfile: ./server/Dockerfile  
#         registry: docker.io
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}

#     - name: Build and Push Docker Image - Worker
#       uses: mr-smithers-excellent/docker-build-push@v4
#       with:
#         image: maheshaila01/codex
#         tags: worker,latest
#         directory: ./worker
#         dockerfile: ./worker/Dockerfile  
#         registry: docker.io
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}


